import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { Col, Row } from 'react-bootstrap'
import Sidebar from './Sidebar'
import Topbar from './Topbar'

export default function Layout({ children }) {
  const route = useRouter()
  const [keys, setKeys] = useState()
  const checkLogin = async () => {
    const keys = await localStorage.getItem('loginKey')
    if(!keys){
      route.push('/admin/login')
      console.log('back')
    }
    setKeys(keys)
  }

  useEffect(()=>{
    checkLogin()
  },[])
  return (
    <div style={{ overflow: "hidden" }}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"></link>
      </Head>
      <Row>
        <Col md={2}>
          <Sidebar />
        </Col>
        <Col>
          <div className='-ml-2'>
            <Topbar />
            <div className='p-3'>
              {children}
            </div>
          </div>
        </Col>
      </Row>
    </div>
  )
}
