import axios from 'axios'
import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import FadeInSection from '../../components/FadeInSection'
import Footer from '../../components/Footer'
import Navbar from '../../components/Navbar'
import SideProduct from '../../components/SideProduct'
import { Config } from '../../config'
import { useRouter } from 'next/router'

export default function Product() {
    const [items, setItems] = useState()
    const [search, setSearch] = useState()
    const [arrItems, setArrItems] = useState()
    const [items1, setItems1] = useState()
    const [items2, setItems2] = useState()
    const router = useRouter()
    const data = router.query

    const chunkArray = (arr, n) => {
        if(arr.length > 0){
            let x = []
            for (let index = 0; index < n; index++) {
                const element = arr[index];
                x.push(element)
            }
            return x
        }
    }
    const getProducts = async () => {
        try {
            const result = await axios.get(`${Config.base_url_api.base}/categories/`)
            const resultSub = await axios.get(`${Config.base_url_api.base}/subcategories/`)
            const resultProd = await axios.get(`${Config.base_url_api.base}/products/?search=${search || ''}`)
            setItems({
                categories: result.data.result,
                sub: resultSub.data.result,
                prod: resultProd.data.result
            })
            console.log(chunkArray(resultProd.data.result, 3), 'res');
            // setItems1(res[0])
            // setItems2(res[1])
        } catch (error) {
            console.log(error);
        }
    }

    useEffect(() => {
        getProducts()
    }, [data, search])
    return (
        <div>
            <Head>
                <title>List Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
                <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"></link>
            </Head>
            <div className='right-bar'>
                <Navbar>
                </Navbar>
            </div>
            <div id='mobile-dev-3'>
                <FadeInSection>
                    <div>
                        <div className='d-product'>
                            <div className='mt-3'>
                                <SideProduct items={items} />
                            </div>
                            <div>
                                <div className='box-product'>
                                    <div className='d-flex flex-row align-items-center justify-content-around'>
                                        <p className='font-product'>{items?.categories?.find((v) => v.ID == data.category_id)?.Name?.toUpperCase() || items?.categories[0]?.Name?.toUpperCase()} / {items?.sub?.find((v) => v.ID == data.subcategory_id)?.Name?.toUpperCase() || items?.sub[0]?.Name?.toUpperCase()}</p>
                                        <div className='float-right'>
                                            <input type={'text'} value={search} onChange={(e) => setSearch(e.target.value)} className='form-control' placeholder='Search' />
                                        </div>
                                    </div>
                                </div>
                                <div className='box-product-2'>
                                    <div style={{ width: '100%', height: '100%', overflow: 'auto ' }}>
                                        {
                                            items1?.filter((v) => v?.Category_id == data?.category_id && v?.Subcategory_id == data?.subcategory_id)?.map((v, i) => (
                                                <p key={v?.ID} className='fs-4'>{`${("-" + v?.Name) || ""}`}</p>
                                            ))
                                        }
                                    </div>
                                    <div style={{ width: '100%', height: '100%', overflow: 'auto ' }}>
                                        {
                                            items2?.filter((v) => v?.Category_id == data?.category_id && v?.Subcategory_id == data?.subcategory_id)?.map((v, i) => (
                                                <p key={v?.ID} className='fs-4'>{`${("-" + v?.Name) || ""}`}</p>
                                            ))
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </FadeInSection>
            </div>
            <Footer />
        </div>
    )
}
